/*******************************************************************************
 *
 *    Copyright (c) 2022 - 2023.
 *    Haixing Hu, Qubit Co. Ltd.
 *
 *    All rights reserved.
 *
 ******************************************************************************/

/**
 * 对URL编码字符串进行解码。
 *
 * @param {String} str
 *   待解码的URL编码字符串。
 * @return {String}
 *   解码结果。
 * @author 胡海星
 */
function uriDecode(str) {
  // The + character is interpreted as a space on the server side as well as
  // generated by forms with spaces in their fields.
  return decodeURIComponent(str.replace(/\+/g, ' '));
}

export default uriDecode;
